##### /api/geotags

### list all
GET http://127.0.0.1:3000/api/geotags

### search with searchterm
GET http://127.0.0.1:3000/api/geotags?searchterm=%23edu

### searcg with position
GET http://127.0.0.1:3000/api/geotags?latitude=49.01379&longitude=8.404435

### search with position AND searcter
GET http://127.0.0.1:3000/api/geotags?latitude=49.01379&longitude=8.404435&searchterm=Buil

### lat wrong
GET http://127.0.0.1:3000/api/geotags?latitude=MOIN&longitude=8.404435

### lon wrong
GET http://127.0.0.1:3000/api/geotags?latitude=6&longitude=bye

### lon missing
GET http://127.0.0.1:3000/api/geotags?latitude=6

### searchterm wrong
GET http://127.0.0.1:3000/api/geotags?searchterm=%23edu55555554

##### /api/geotags/page

GET http://127.0.0.1:3000/api/geotags/page?lastId=3&pageSize=3&searchterm=Building

##### POST /api/geotags

### bad
POST http://127.0.0.1:3000/api/geotags
content-type: application/json

{
    "name": "49.01379",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "longitude": 8.404435
}

### ok
POST http://127.0.0.1:3000/api/geotags
content-type: application/json

{
    "latitude": 49.01379,
    "longitude": 8.404435,
    "name": "moin",
    "hashtag": "#hello"
}

##### GET /api/geotags/:id

### ok
GET http://127.0.0.1:3000/api/geotags/5

### :(
GET http://127.0.0.1:3000/api/geotags/-1

##### PUT /api/geotags/:id

### ok
PUT http://127.0.0.1:3000/api/geotags/5
content-type: application/json

{
    "latitude": 49.01379,
    "longitude": 8.404435,
    "name": "moin",
    "hashtag": "#hello"
}

### Bad
PUT http://127.0.0.1:3000/api/geotags/5
content-type: application/json

{
    "name": "49.01379",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "longitude": 8.404435
}

##### DELETE /api/geotags/:id
DELETE http://127.0.0.1:3000/api/geotags/5
